// <auto-generated />
using System;
using Loan.WebApi.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Loan.WebApi.Migrations
{
    [DbContext(typeof(LoanContext))]
    [Migration("20201211004747_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("LOAN")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Loan.WebApi.Domain.Entities.Emprestimo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("Data")
                        .HasColumnName("DATA")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnName("DATACRIACAO")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("Devolucao")
                        .HasColumnName("DEVOLUCAO")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<long>("PessoaId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK_EMPRESTIMO_ID");

                    b.HasIndex("ItemId");

                    b.HasIndex("PessoaId");

                    b.ToTable("EMPRESTIMO");
                });

            modelBuilder.Entity("Loan.WebApi.Domain.Entities.Item", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnName("DATACRIACAO")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Nome")
                        .HasColumnName("NOME")
                        .HasColumnType("text");

                    b.Property<int>("Tipo")
                        .HasColumnName("TIPO")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("PK_ITEM_ID");

                    b.ToTable("ITEM");
                });

            modelBuilder.Entity("Loan.WebApi.Domain.Entities.Pessoa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnName("DATACRIACAO")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasColumnName("EMAIL")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .HasColumnName("NOME")
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .HasColumnName("TELEFONE")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("PK_PESSOA_ID");

                    b.ToTable("PESSOA");
                });

            modelBuilder.Entity("Loan.WebApi.Domain.Entities.Emprestimo", b =>
                {
                    b.HasOne("Loan.WebApi.Domain.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Loan.WebApi.Domain.Entities.Pessoa", "Pessoa")
                        .WithMany("Emprestimos")
                        .HasForeignKey("PessoaId")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
